
# This is an example configuration block
webclient.builder:
  webclients:
    - name: Test1
      baseUrl: http://localhost:8080/
      connectionTimeout: 1000
      oauth:
        clientId: test1
        clientSecret: testsecret1
        grantType: client_credentials
        scope: test1
        tokenUrl: http://localhost:8080/oauth/token

# Setting Logger to Debug will output configuration for each webclient.
logging:
  level:
    com.github.jander99.webclientbuilder.autoconfigure: debug